language: node_js
sudo: required
dist: trusty
matrix:
  include:
  - node_js: 6
  - node_js: 8
  - node_js: 6
    env: SAUCE=true
before_install:
- npm install -g npm@'>=2.13.5'
script:
- |
  echo "machine github.com login stellar-jenkins password $GITHUB_TOKEN" >~/.netrc
  git config --global user.name "Travis CI"
  git config --global user.email "travis@stellar.org"
  if [ "${SAUCE}" = "true" ]; then
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      gulp test:sauce
    else
      echo "Pull request - skip Sauce Labs testing..."
    fi
  else
    # Ugly but it's the only way to make istanbul generate coverage report
    babel-node ./node_modules/gulp/bin/gulp.js test:node
  fi
after_success:
- |
  # Send report to coveralls but only once
  if [ -z "${SAUCE}" ] && [ "${TRAVIS_NODE_VERSION}" = "8" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    gulp submit-coverage
  fi
notifications:
  slack:
    secure: CgXxNEQrQ82EatyF/wSdF0P5rXcWPL+fFZ1lb1aBb8RbVt5gwddJ6xWVD/nYSr6tIJvIYHYhoYsIDPENwezIPsesG7kWXerQhydsEcA34JKxzsStd/TmU6Moxuwy6KTN7yzmL6586nSvoAw9TNPgvRkJFkH07asjGIc9Rlaq7/Y=
env:
  global:
  - secure: UfHc1SSKsUx8j2Z/S9WoJA+Qd9T9tWQZEGZVzmAmkGQ+V4iQsYwp2AwWJLH+e0JSKcVz9tiGicPfv8RlVS4YAQ2EeW2kC2W0ULrX4FYwNuuD/tjfHl47Vsoze4QlBuaZd897upt8r30GpUhqLonAkKr3700lZjr9Id3woWrSNfA=
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_deploy: gulp build
after_deploy: "./after_deploy.sh"
deploy:
  - provider: npm
    email: npm@stellar.org
    api_key:
      secure: SZIsdOgh5eg+i1JSqLYTDv2EgYQTX54LIICX3BpSYjhqCBGeWxGXYhAGtVnBVVxslV1zZNe/H73hdKLMjd58DAda7hQXfrNKaRbijVH4B0ZHsFxyF20919G+GcqiWAeNGfe640SsqStipxXnJegHjVF5r6tmYZS3fmjkZ9Ndqn0=
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-base
      node: 8
  - provider: script
    script: "./bower_publish.sh"
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-base
      node: 8
